package io.openshift.booster.database;

import io.reactivex.Completable;
import io.reactivex.Flowable;
import io.vertx.ext.sql.SQLOptions;
import io.vertx.reactivex.core.Vertx;
import io.vertx.reactivex.ext.jdbc.JDBCClient;


/**
 * Simple helper to bootstrap your Database.
 *
 * @author Paulo Lopes
 */
public class DBInitHelper {

  private DBInitHelper() {
    // Private constructor.
  }

  static Completable initDatabase(Vertx vertx, JDBCClient jdbc) {
    return jdbc.rxGetConnection()
      .map(c -> c.setOptions(new SQLOptions().setAutoGeneratedKeys(true)))
      .flatMapCompletable(connection ->
        vertx.fileSystem().rxReadFile("ddl.sql")
          .flatMapPublisher(buffer -> Flowable.fromArray(buffer.toString().split(";")))
          .flatMapCompletable(connection::rxExecute)
          .doAfterTerminate(connection::close)
      );
  }
}
